### ISSUE TITLE
Don't touch my settings

### ISSUE THREAD

**Issue by Scorg** [Enkel-Digital/relativity#10]
Why the hell does it need to change my settings?

**Comment by Jaimeloeuf** [comment]
hi @Scorg since the extension allows you to move around using relative line numbers, your editor needs to show relative line numbers for this to work, which is why during setup, it changes the line numbers from Absolute to Relative.

Without this change, the extension doesnt make any sense at all.

Here is the setting it changed
https://github.com/Jaimeloeuf/relativity/blob/master/src/setup.ts

You can change it back if it is not something you want anymore, thanks!
